name: TOPCAFES
run-name: TOPCAFES

on:
  # Запускає workflow при пушах в основну гілку
  push:
    branches:
      - 'main'

  # Дозволяє запускати цей workflow вручну через вкладку Actions в GitHub
  workflow_dispatch:

# Дозволяє записувати зміни в контент
permissions:
  contents: write

# Дозволяє одночасне розгортання і скасовує поточне, якщо є нове
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Робота зі збіркою та розгортанням
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # Клонування репозиторію

      - uses: actions/setup-node@v4
        with:
          version: 20
        # Налаштування Node.js версії 20

      - name: Install Dependencies
        run: npm install
        # Встановлення всіх необхідних пакетів

      - name: Build
        run: npm run build
        env:
          PUBLIC_API_URL: https://liliabilous.github.io/TOPCAFES/
        # Збірка проекту, команда `npm run build` запускає скрипт, що визначений у вашому `package.json`

      - name: Copy to gh-pages-demo branch
        run: |
          git fetch origin
          git checkout gh-pages-demo
          git pull origin gh-pages-demo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          cp -r dist/* .
          git add .
          git commit -m "Deploy to gh-pages-demo branch" || echo "No changes to commit"
          git push origin gh-pages-demo
        # Налаштування Git для комітів, перемикання на гілку `gh-pages-demo`, копіювання зібраних файлів з `dist`, коміт і пуш

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./dist
        # Розгортання файлів з папки `dist` на GitHub Pages
