name: Deploy to Github Pages
run-name: TOPCAFES

on:
  push:
    branches:
      - "main"


jobs:
  # Робота зі збіркою та розгортанням
  build:
    name: Build # Defines the name of the build job.
    runs-on: ubuntu-latest # Specifies the operating system for the job.
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # Клонування репозиторію

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
        # Налаштування Node.js з кешуванням залежностей

      - name: Install Dependencies
        run: npm install
        # Встановлення всіх необхідних пакетів

      - name: Build
        run: npm run build
        env:
          PUBLIC_API_URL: https://liliabilous.github.io/TOPCAFES/
        # Збірка проекту, команда `npm run build` запускає скрипт, що визначений у вашому `package.json`

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
        # Налаштування Git для комітів

      - name: Save changes and switch branches
        run: |
          git fetch origin
          git add .
          git commit -m "Save current changes before switching branches" || echo "No changes to commit"
          git checkout gh-pages-demo || git checkout -b gh-pages-demo
          git pull origin gh-pages-demo
        # Збереження поточних змін, переключення на гілку `gh-pages-demo`, якщо вона існує, і пул останніх змін

      - name: Copy and deploy
        run: |
          cp -r dist/* .
          git add .
          git commit -m "Deploy to gh-pages-demo branch" || echo "No changes to commit"
          git push origin gh-pages-demo
        # Копіювання зібраних файлів з `dist`, коміт і пуш на гілку `gh-pages-demo`

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./dist
        # Розгортання файлів з папки `dist` на GitHub Pages
